import { Beach } from "../models/beach";

export const beachesList: Beach[] = [
  {
    "id": "4415",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/445.webp",
    "name": "Abadejos",
    "island": "La Palma",
    "municipality": "Fuencaliente de la Palma",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": true,
    "latitude": 28.4690372801722,
    "longitude": -17.8644751797917,
    "length": 100,
    "blueFlag": false
  },
  {
    "id": "5144",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/544.webp",
    "name": "Abades",
    "island": "Tenerife",
    "municipality": "Arico",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "HIGH",
    "classification": "FREE",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.1353953904194,
    "longitude": -16.4457372159306,
    "length": 130,
    "blueFlag": false
  },
  {
    "id": "7151",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/751.webp",
    "name": "Agua Dulce",
    "island": "Tenerife",
    "municipality": "Los Silos",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.3762518293778,
    "longitude": -16.809049859175,
    "length": 200,
    "blueFlag": false
  },
  {
    "id": "5313",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/533.webp",
    "name": "Aguadulce",
    "island": "Tenerife",
    "municipality": "Arico",
    "accessByCar": false,
    "accessByFoot": "DIFFICULT",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": true,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.1917338432194,
    "longitude": -16.4252922284917,
    "length": 110,
    "blueFlag": false
  },
  {
    "id": "5126",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/526.webp",
    "name": "Ajabo",
    "island": "Tenerife",
    "municipality": "Adeje",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "FREE",
    "environmentCondition": "SEMI_URBAN",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": true,
    "hasToilets": false,
    "latitude": 28.1274302538583,
    "longitude": -16.7819769629944,
    "length": 100,
    "blueFlag": true
  },
  {
    "id": "1158",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/58.webp",
    "name": "Ajuy",
    "island": "Fuerteventura",
    "municipality": "Pájara",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": true,
    "hasToilets": true,
    "latitude": 28.3992049823667,
    "longitude": -14.1563440339611,
    "length": 270,
    "blueFlag": false
  },
  {
    "id": "4111",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/411.webp",
    "name": "Alojera",
    "island": "La Gomera",
    "municipality": "Vallehermoso",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "DANGEROUS",
    "environmentCondition": "SEMI_URBAN",
    "hasRock": true,
    "hasSand": true,
    "hasShowers": true,
    "hasToilets": true,
    "latitude": 28.1640699108222,
    "longitude": -17.3345495853111,
    "length": 300,
    "blueFlag": false
  },
  {
    "id": "3011",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/30.webp",
    "name": "Alzada",
    "island": "Fuerteventura",
    "municipality": "La Oliva",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "FREE",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.6727583989194,
    "longitude": -13.8334434485278,
    "length": 840,
    "blueFlag": false
  },
  {
    "id": "2741",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/274.webp",
    "name": "Amadores",
    "island": "Gran Canaria",
    "municipality": "Mogán",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "HIGH",
    "classification": "FREE",
    "environmentCondition": "URBAN",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": true,
    "hasToilets": true,
    "latitude": 27.7910830406278,
    "longitude": -15.7248945608694,
    "length": 488,
    "blueFlag": true
  },
  {
    "id": "7001",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/700.webp",
    "name": "Amarilla",
    "island": "Tenerife",
    "municipality": "San Miguel de Abona",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "SEMI_URBAN",
    "hasRock": true,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.0092923386472,
    "longitude": -16.63791984835,
    "length": 50,
    "blueFlag": false
  },
  {
    "id": "2681",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/268.webp",
    "name": "Aquamarina",
    "island": "Gran Canaria",
    "municipality": "Mogán",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "FREE",
    "environmentCondition": "URBAN",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 27.7716962924194,
    "longitude": -15.6921048854722,
    "length": 80,
    "blueFlag": false
  },
  {
    "id": "4181",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/418.webp",
    "name": "Arenas Blancas",
    "island": "El Hierro",
    "municipality": "Frontera",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": true,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 27.7664737805917,
    "longitude": -18.1215147638556,
    "length": 50,
    "blueFlag": false
  },
  {
    "id": "4101",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/410.webp",
    "name": "Argaga",
    "island": "La Gomera",
    "municipality": "Vallehermoso",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": true,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": true,
    "latitude": 28.0791969501528,
    "longitude": -17.3235446935556,
    "length": 350,
    "blueFlag": false
  },
  {
    "id": "4131",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/413.webp",
    "name": "Arguamul",
    "island": "La Gomera",
    "municipality": "Vallehermoso",
    "accessByCar": false,
    "accessByFoot": "DIFFICULT",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": true,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": true,
    "latitude": 28.206776180375,
    "longitude": -17.2952248818083,
    "length": 700,
    "blueFlag": false
  },
  {
    "id": "2621",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/262.webp",
    "name": "Arguineguín",
    "island": "Gran Canaria",
    "municipality": "Mogán",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "MEDIUM",
    "classification": "FREE",
    "environmentCondition": "URBAN",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 27.7562197925389,
    "longitude": -15.6813509827778,
    "length": 241,
    "blueFlag": true
  },
  {
    "id": "2391",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/239.webp",
    "name": "Arrastradero",
    "island": "Gran Canaria",
    "municipality": "Gáldar",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": false,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.1369818085139,
    "longitude": -15.6995654210167,
    "length": 60,
    "blueFlag": false
  },
  {
    "id": "3817",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/387.webp",
    "name": "Avalo",
    "island": "La Gomera",
    "municipality": "San Sebastián de la Gomera",
    "accessByCar": true,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "DANGEROUS",
    "environmentCondition": "SEMI_URBAN",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 28.1116911304611,
    "longitude": -17.1059673668222,
    "length": 350,
    "blueFlag": false
  },
  {
    "id": "1381",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/138.webp",
    "name": "Bahía del Salado",
    "island": "Lanzarote",
    "municipality": "Teguise",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "FREE",
    "environmentCondition": "ISOLATED",
    "hasRock": false,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 29.2260386942,
    "longitude": -13.5052246390333,
    "length": 1800,
    "blueFlag": false
  },
  {
    "id": "1010",
    "coverUrl": "https://api.playea.eu/storage/public/beaches/100.webp",
    "name": "Baja Piquiento",
    "island": "Lanzarote",
    "municipality": "Haría",
    "accessByCar": false,
    "accessByFoot": "EASY",
    "annualMaxOccupancy": "LOW",
    "classification": "FREE",
    "environmentCondition": "ISOLATED",
    "hasRock": true,
    "hasSand": true,
    "hasShowers": false,
    "hasToilets": false,
    "latitude": 29.1537025041028,
    "longitude": -13.4349431497889,
    "length": 100,
    "blueFlag": false
  }
];